name: Deploy public repo with Apps
on:
  workflow_dispatch:

jobs:
  build:
    name: Setup
    runs-on: ubuntu-24.04
    environment: FOR_PROGRESS_BAR
    permissions:
      actions: write
      checks: write
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Debug permissions
        run: |
          gh api "/repos/takkaO/pub_test2" --jq '{name, permissions}'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set git-configs
        run: |
          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git config push.default current
      
      - name: Git push
        run: |
          git push ${{ secrets.PUBLIC_REMOTE_REPOSITORY2 }} main --tags